import 'package:flutter/material.dart';
import 'package:icons_flutter/src/icons_flutter_data.dart';

/// all Icons under EvilIcons
///
/// http://evil-icons.io
class EvilIcons {
  EvilIcons._();
  static const String _family = "EvilIcons";
  static const IconData archive = IconData(61696, fontFamily: _family, fontPackage: fontPackage);
  static const IconData arrow_down = IconData(61697, fontFamily: _family, fontPackage: fontPackage);
  static const IconData arrow_left = IconData(61698, fontFamily: _family, fontPackage: fontPackage);
  static const IconData arrow_right = IconData(61699, fontFamily: _family, fontPackage: fontPackage);
  static const IconData arrow_up = IconData(61700, fontFamily: _family, fontPackage: fontPackage);
  static const IconData bell = IconData(61701, fontFamily: _family, fontPackage: fontPackage);
  static const IconData calendar = IconData(61702, fontFamily: _family, fontPackage: fontPackage);
  static const IconData camera = IconData(61703, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cart = IconData(61704, fontFamily: _family, fontPackage: fontPackage);
  static const IconData chart = IconData(61705, fontFamily: _family, fontPackage: fontPackage);
  static const IconData check = IconData(61706, fontFamily: _family, fontPackage: fontPackage);
  static const IconData chevron_down = IconData(61707, fontFamily: _family, fontPackage: fontPackage);
  static const IconData chevron_left = IconData(61708, fontFamily: _family, fontPackage: fontPackage);
  static const IconData chevron_right = IconData(61709, fontFamily: _family, fontPackage: fontPackage);
  static const IconData chevron_up = IconData(61710, fontFamily: _family, fontPackage: fontPackage);
  static const IconData clock = IconData(61711, fontFamily: _family, fontPackage: fontPackage);
  static const IconData close = IconData(61712, fontFamily: _family, fontPackage: fontPackage);
  static const IconData close_o = IconData(61713, fontFamily: _family, fontPackage: fontPackage);
  static const IconData comment = IconData(61714, fontFamily: _family, fontPackage: fontPackage);
  static const IconData credit_card = IconData(61715, fontFamily: _family, fontPackage: fontPackage);
  static const IconData envelope = IconData(61716, fontFamily: _family, fontPackage: fontPackage);
  static const IconData exclamation = IconData(61717, fontFamily: _family, fontPackage: fontPackage);
  static const IconData external_link = IconData(61718, fontFamily: _family, fontPackage: fontPackage);
  static const IconData eye = IconData(61719, fontFamily: _family, fontPackage: fontPackage);
  static const IconData gear = IconData(61720, fontFamily: _family, fontPackage: fontPackage);
  static const IconData heart = IconData(61721, fontFamily: _family, fontPackage: fontPackage);
  static const IconData image = IconData(61722, fontFamily: _family, fontPackage: fontPackage);
  static const IconData like = IconData(61723, fontFamily: _family, fontPackage: fontPackage);
  static const IconData link = IconData(61724, fontFamily: _family, fontPackage: fontPackage);
  static const IconData location = IconData(61725, fontFamily: _family, fontPackage: fontPackage);
  static const IconData lock = IconData(61726, fontFamily: _family, fontPackage: fontPackage);
  static const IconData minus = IconData(61727, fontFamily: _family, fontPackage: fontPackage);
  static const IconData navicon = IconData(61728, fontFamily: _family, fontPackage: fontPackage);
  static const IconData paperclip = IconData(61729, fontFamily: _family, fontPackage: fontPackage);
  static const IconData pencil = IconData(61730, fontFamily: _family, fontPackage: fontPackage);
  static const IconData play = IconData(61731, fontFamily: _family, fontPackage: fontPackage);
  static const IconData plus = IconData(61732, fontFamily: _family, fontPackage: fontPackage);
  static const IconData pointer = IconData(61733, fontFamily: _family, fontPackage: fontPackage);
  static const IconData question = IconData(61734, fontFamily: _family, fontPackage: fontPackage);
  static const IconData redo = IconData(61735, fontFamily: _family, fontPackage: fontPackage);
  static const IconData refresh = IconData(61736, fontFamily: _family, fontPackage: fontPackage);
  static const IconData retweet = IconData(61737, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_facebook = IconData(61738, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_github = IconData(61739, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_google_plus = IconData(61740, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_instagram = IconData(61741, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_linkedin = IconData(61742, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_odnoklassniki = IconData(61743, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_pinterest = IconData(61744, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_skype = IconData(61745, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_soundcloud = IconData(61746, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_telegram = IconData(61747, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_tumblr = IconData(61748, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_twitter = IconData(61749, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_vimeo = IconData(61750, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_vk = IconData(61751, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sc_youtube = IconData(61752, fontFamily: _family, fontPackage: fontPackage);
  static const IconData search = IconData(61753, fontFamily: _family, fontPackage: fontPackage);
  static const IconData share_apple = IconData(61754, fontFamily: _family, fontPackage: fontPackage);
  static const IconData share_google = IconData(61755, fontFamily: _family, fontPackage: fontPackage);
  static const IconData spinner = IconData(61756, fontFamily: _family, fontPackage: fontPackage);
  static const IconData spinner_2 = IconData(61757, fontFamily: _family, fontPackage: fontPackage);
  static const IconData spinner_3 = IconData(61758, fontFamily: _family, fontPackage: fontPackage);
  static const IconData star = IconData(61759, fontFamily: _family, fontPackage: fontPackage);
  static const IconData tag = IconData(61760, fontFamily: _family, fontPackage: fontPackage);
  static const IconData trash = IconData(61761, fontFamily: _family, fontPackage: fontPackage);
  static const IconData trophy = IconData(61762, fontFamily: _family, fontPackage: fontPackage);
  static const IconData undo = IconData(61763, fontFamily: _family, fontPackage: fontPackage);
  static const IconData unlock = IconData(61764, fontFamily: _family, fontPackage: fontPackage);
  static const IconData user = IconData(61765, fontFamily: _family, fontPackage: fontPackage);
}
