import 'package:flutter/widgets.dart';
import 'package:icons_flutter/src/icons_flutter_data.dart';

class Linecons {
  Linecons._();

  static const IconData music = IconsFlutterData.lineCons(0xe800);
  static const IconData search = IconsFlutterData.lineCons(0xe801);
  static const IconData mail = IconsFlutterData.lineCons(0xe802);
  static const IconData heart = IconsFlutterData.lineCons(0xe803);
  static const IconData star = IconsFlutterData.lineCons(0xe804);
  static const IconData user = IconsFlutterData.lineCons(0xe805);
  static const IconData videocam = IconsFlutterData.lineCons(0xe806);
  static const IconData camera = IconsFlutterData.lineCons(0xe807);
  static const IconData photo = IconsFlutterData.lineCons(0xe808);
  static const IconData attach = IconsFlutterData.lineCons(0xe809);
  static const IconData lock = IconsFlutterData.lineCons(0xe80a);
  static const IconData eye = IconsFlutterData.lineCons(0xe80b);
  static const IconData tag = IconsFlutterData.lineCons(0xe80c);
  static const IconData thumbs_up = IconsFlutterData.lineCons(0xe80d);
  static const IconData pencil = IconsFlutterData.lineCons(0xe80e);
  static const IconData comment = IconsFlutterData.lineCons(0xe80f);
  static const IconData location = IconsFlutterData.lineCons(0xe810);
  static const IconData cup = IconsFlutterData.lineCons(0xe811);
  static const IconData trash = IconsFlutterData.lineCons(0xe812);
  static const IconData doc = IconsFlutterData.lineCons(0xe813);
  static const IconData note = IconsFlutterData.lineCons(0xe814);
  static const IconData cog = IconsFlutterData.lineCons(0xe815);
  static const IconData params = IconsFlutterData.lineCons(0xe816);
  static const IconData calendar = IconsFlutterData.lineCons(0xe817);
  static const IconData sound = IconsFlutterData.lineCons(0xe818);
  static const IconData clock = IconsFlutterData.lineCons(0xe819);
  static const IconData lightbulb = IconsFlutterData.lineCons(0xe81a);
  static const IconData tv = IconsFlutterData.lineCons(0xe81b);
  static const IconData desktop = IconsFlutterData.lineCons(0xe81c);
  static const IconData mobile = IconsFlutterData.lineCons(0xe81d);
  static const IconData cd = IconsFlutterData.lineCons(0xe81e);
  static const IconData inbox = IconsFlutterData.lineCons(0xe81f);
  static const IconData globe = IconsFlutterData.lineCons(0xe820);
  static const IconData cloud = IconsFlutterData.lineCons(0xe821);
  static const IconData paper_plane = IconsFlutterData.lineCons(0xe822);
  static const IconData fire = IconsFlutterData.lineCons(0xe823);
  static const IconData graduation_cap = IconsFlutterData.lineCons(0xe824);
  static const IconData megaphone = IconsFlutterData.lineCons(0xe825);
  static const IconData database = IconsFlutterData.lineCons(0xe826);
  static const IconData key = IconsFlutterData.lineCons(0xe827);
  static const IconData beaker = IconsFlutterData.lineCons(0xe828);
  static const IconData truck = IconsFlutterData.lineCons(0xe829);
  static const IconData money = IconsFlutterData.lineCons(0xe82a);
  static const IconData food = IconsFlutterData.lineCons(0xe82b);
  static const IconData shop = IconsFlutterData.lineCons(0xe82c);
  static const IconData diamond = IconsFlutterData.lineCons(0xe82d);
  static const IconData t_shirt = IconsFlutterData.lineCons(0xe82e);
  static const IconData wallet = IconsFlutterData.lineCons(0xe82f);
}
