import 'package:flutter/widgets.dart';
import 'package:icons_flutter/src/icons_flutter_data.dart';

class Maki {
  Maki._();

  static const IconData aboveground_rail = IconsFlutterData.maki(0xe800);
  static const IconData airfield = IconsFlutterData.maki(0xe801);
  static const IconData airport = IconsFlutterData.maki(0xe802);
  static const IconData art_gallery = IconsFlutterData.maki(0xe803);
  static const IconData bar = IconsFlutterData.maki(0xe804);
  static const IconData baseball = IconsFlutterData.maki(0xe806);
  static const IconData basketball = IconsFlutterData.maki(0xe807);
  static const IconData beer = IconsFlutterData.maki(0xe808);
  static const IconData belowground_rail = IconsFlutterData.maki(0xe809);
  static const IconData bicycle = IconsFlutterData.maki(0xe80a);
  static const IconData bus = IconsFlutterData.maki(0xe80b);
  static const IconData cafe = IconsFlutterData.maki(0xe80c);
  static const IconData campsite = IconsFlutterData.maki(0xe80d);
  static const IconData cemetery = IconsFlutterData.maki(0xe80e);
  static const IconData cinema = IconsFlutterData.maki(0xe80f);
  static const IconData college = IconsFlutterData.maki(0xe810);
  static const IconData commerical_building = IconsFlutterData.maki(0xe811);
  static const IconData credit_card = IconsFlutterData.maki(0xe812);
  static const IconData cricket = IconsFlutterData.maki(0xe813);
  static const IconData embassy = IconsFlutterData.maki(0xe814);
  static const IconData fast_food = IconsFlutterData.maki(0xe815);
  static const IconData ferry = IconsFlutterData.maki(0xe816);
  static const IconData fire_station = IconsFlutterData.maki(0xe817);
  static const IconData football = IconsFlutterData.maki(0xe818);
  static const IconData fuel = IconsFlutterData.maki(0xe819);
  static const IconData garden = IconsFlutterData.maki(0xe81a);
  static const IconData giraffe = IconsFlutterData.maki(0xe81b);
  static const IconData golf = IconsFlutterData.maki(0xe81c);
  static const IconData grocery_store = IconsFlutterData.maki(0xe81e);
  static const IconData harbor = IconsFlutterData.maki(0xe81f);
  static const IconData heliport = IconsFlutterData.maki(0xe820);
  static const IconData hospital = IconsFlutterData.maki(0xe821);
  static const IconData industrial_building = IconsFlutterData.maki(0xe822);
  static const IconData library_icon = IconsFlutterData.maki(0xe823);
  static const IconData lodging = IconsFlutterData.maki(0xe824);
  static const IconData london_underground = IconsFlutterData.maki(0xe825);
  static const IconData minefield = IconsFlutterData.maki(0xe826);
  static const IconData monument = IconsFlutterData.maki(0xe827);
  static const IconData museum = IconsFlutterData.maki(0xe828);
  static const IconData pharmacy = IconsFlutterData.maki(0xe829);
  static const IconData pitch = IconsFlutterData.maki(0xe82a);
  static const IconData police = IconsFlutterData.maki(0xe82b);
  static const IconData post = IconsFlutterData.maki(0xe82c);
  static const IconData prison = IconsFlutterData.maki(0xe82d);
  static const IconData rail = IconsFlutterData.maki(0xe82e);
  static const IconData religious_christian = IconsFlutterData.maki(0xe82f);
  static const IconData religious_islam = IconsFlutterData.maki(0xe830);
  static const IconData religious_jewish = IconsFlutterData.maki(0xe831);
  static const IconData restaurant = IconsFlutterData.maki(0xe832);
  static const IconData roadblock = IconsFlutterData.maki(0xe833);
  static const IconData school = IconsFlutterData.maki(0xe834);
  static const IconData shop = IconsFlutterData.maki(0xe835);
  static const IconData skiing = IconsFlutterData.maki(0xe836);
  static const IconData soccer = IconsFlutterData.maki(0xe837);
  static const IconData swimming = IconsFlutterData.maki(0xe838);
  static const IconData tennis = IconsFlutterData.maki(0xe839);
  static const IconData theatre = IconsFlutterData.maki(0xe83a);
  static const IconData toilet = IconsFlutterData.maki(0xe83b);
  static const IconData town_hall = IconsFlutterData.maki(0xe83c);
  static const IconData trash = IconsFlutterData.maki(0xe83d);
  static const IconData tree_1 = IconsFlutterData.maki(0xe83e);
  static const IconData tree_2 = IconsFlutterData.maki(0xe83f);
  static const IconData warehouse = IconsFlutterData.maki(0xe840);
}
