import 'package:flutter/widgets.dart';
import 'package:icons_flutter/src/icons_flutter_data.dart';

class Meteocons {
  Meteocons._();

  static const String _family = "Meteocons";
  static const IconData windy_rain_inv = IconData(0xe800, fontFamily: _family, fontPackage: fontPackage);
  static const IconData snow_inv = IconData(0xe801, fontFamily: _family, fontPackage: fontPackage);
  static const IconData snow_heavy_inv = IconData(0xe802, fontFamily: _family, fontPackage: fontPackage);
  static const IconData hail_inv = IconData(0xe803, fontFamily: _family, fontPackage: fontPackage);
  static const IconData clouds_inv = IconData(0xe804, fontFamily: _family, fontPackage: fontPackage);
  static const IconData clouds_flash_inv = IconData(0xe805, fontFamily: _family, fontPackage: fontPackage);
  static const IconData temperature = IconData(0xe806, fontFamily: _family, fontPackage: fontPackage);
  static const IconData compass = IconData(0xe807, fontFamily: _family, fontPackage: fontPackage);
  static const IconData na = IconData(0xe808, fontFamily: _family, fontPackage: fontPackage);
  static const IconData celcius = IconData(0xe809, fontFamily: _family, fontPackage: fontPackage);
  static const IconData fahrenheit = IconData(0xe80a, fontFamily: _family, fontPackage: fontPackage);
  static const IconData clouds_flash_alt = IconData(0xe80b, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sun_inv = IconData(0xe80c, fontFamily: _family, fontPackage: fontPackage);
  static const IconData moon_inv = IconData(0xe80d, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_sun_inv = IconData(0xe80e, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_moon_inv = IconData(0xe80f, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_inv = IconData(0xe810, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_flash_inv = IconData(0xe811, fontFamily: _family, fontPackage: fontPackage);
  static const IconData drizzle_inv = IconData(0xe812, fontFamily: _family, fontPackage: fontPackage);
  static const IconData rain_inv = IconData(0xe813, fontFamily: _family, fontPackage: fontPackage);
  static const IconData windy_inv = IconData(0xe814, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sunrise = IconData(0xe815, fontFamily: _family, fontPackage: fontPackage);
  static const IconData sun = IconData(0xe816, fontFamily: _family, fontPackage: fontPackage);
  static const IconData moon = IconData(0xe817, fontFamily: _family, fontPackage: fontPackage);
  static const IconData eclipse = IconData(0xe818, fontFamily: _family, fontPackage: fontPackage);
  static const IconData mist = IconData(0xe819, fontFamily: _family, fontPackage: fontPackage);
  static const IconData wind = IconData(0xe81a, fontFamily: _family, fontPackage: fontPackage);
  static const IconData snowflake = IconData(0xe81b, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_sun = IconData(0xe81c, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_moon = IconData(0xe81d, fontFamily: _family, fontPackage: fontPackage);
  static const IconData fog_sun = IconData(0xe81e, fontFamily: _family, fontPackage: fontPackage);
  static const IconData fog_moon = IconData(0xe81f, fontFamily: _family, fontPackage: fontPackage);
  static const IconData fog_cloud = IconData(0xe820, fontFamily: _family, fontPackage: fontPackage);
  static const IconData fog = IconData(0xe821, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud = IconData(0xe822, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_flash = IconData(0xe823, fontFamily: _family, fontPackage: fontPackage);
  static const IconData cloud_flash_alt = IconData(0xe824, fontFamily: _family, fontPackage: fontPackage);
  static const IconData drizzle = IconData(0xe825, fontFamily: _family, fontPackage: fontPackage);
  static const IconData rain = IconData(0xe826, fontFamily: _family, fontPackage: fontPackage);
  static const IconData windy = IconData(0xe827, fontFamily: _family, fontPackage: fontPackage);
  static const IconData windy_rain = IconData(0xe828, fontFamily: _family, fontPackage: fontPackage);
  static const IconData snow = IconData(0xe829, fontFamily: _family, fontPackage: fontPackage);
  static const IconData snow_alt = IconData(0xe82a, fontFamily: _family, fontPackage: fontPackage);
  static const IconData snow_heavy = IconData(0xe82b, fontFamily: _family, fontPackage: fontPackage);
  static const IconData hail = IconData(0xe82c, fontFamily: _family, fontPackage: fontPackage);
  static const IconData clouds = IconData(0xe82d, fontFamily: _family, fontPackage: fontPackage);
  static const IconData clouds_flash = IconData(0xe82e, fontFamily: _family, fontPackage: fontPackage);
}
